import { isArtifactRootName } from "./artifacts";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import {
  polarityLabel,
  renderThreshold,
  worseSide,
  worseSideComparison,
  type Measures,
} from "./measures";

export type KnownIdInfo = {
  ids: string[];
  moduleName: string;
};

// cwd非依存にするため、specディレクトリをcwdにして "." を渡す。
export function fetchKnownIds(specPath: string): string[] {
  const result = spawnSync("cue", ["export", ".", "-e", "knownIds"], {
    cwd: resolve(specPath),
    encoding: "utf-8",
  });
  if (result.status !== 0) {
    throw new Error(`cue export failed:\n${result.stderr}`);
  }
  return JSON.parse(result.stdout) as string[];
}

// 測度の宣言(任意)。無いspecでは undefined を返し、測度の機構を丸ごと使わない
// ("健全だが完全ではない" — 数値尺度を持たないシステムに負担を課さない)。
export function fetchMeasures(specPath: string): Measures | undefined {
  const result = spawnSync("cue", ["export", ".", "-e", "measures"], {
    cwd: resolve(specPath),
    encoding: "utf-8",
  });
  if (result.status !== 0) {
    return undefined;
  }
  try {
    return JSON.parse(result.stdout) as Measures;
  } catch {
    return undefined;
  }
}

export function moduleNameFor(specPath: string): string {
  const segments = specPath.split("/").filter(Boolean);
  const base = segments.pop() ?? "spec";
  // spec ディレクトリの直親をアプリ名とみなす。
  let appDir = base === "spec" ? segments[segments.length - 1] : base;
  // 直親が時刻付き成果物ルート（または従来の keaton）なら、
  // その一つ上(プロジェクト名)を使う。
  if (appDir === "keaton" || isArtifactRootName(appDir ?? "")) {
    appDir = segments[segments.length - 2] ?? appDir;
  }
  return `${toIdentifier(appDir ?? "spec")}Constants`;
}

// アプリディレクトリ名から有効なQuint識別子を作る。
// ハイフン等の非英数字で区切り、各片の先頭を大文字にして繋ぐ。
// 例: "momotaro"→"Momotaro", "todo-cli"→"TodoCli"
function toIdentifier(name: string): string {
  const parts = name.split(/[^a-zA-Z0-9]+/).filter((part) => part.length > 0);
  if (parts.length === 0) {
    return "Spec";
  }
  return parts.map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

export function toQuintName(id: string): string {
  const parts = id.split("-").filter((part) => part.length > 0);
  if (parts.length === 1) {
    return parts[0];
  }
  return parts
    .map((part, index) =>
      index === 0 ? part : part[0].toUpperCase() + part.slice(1),
    )
    .join("");
}

export type ThresholdQuintNames = {
  at: string;
  isWorseSide: string;
  isBetterSide: string;
};

// 閾値から生成するQuint記号名の決定を、生成側と使用検査側で共有する。
export function thresholdQuintNames(thresholdId: string): ThresholdQuintNames {
  const name = toQuintName(thresholdId);
  return {
    at: `${name}At`,
    isWorseSide: `${name}IsWorseSide`,
    isBetterSide: `${name}IsBetterSide`,
  };
}

// 測度から、閾値の定数と「どちら側を検出するか」を名前に持つ述語を生成する。
// 比較の向きはCUEの極性から導出されるので、振る舞いモデルは v >= 3 のような
// 生の比較を書かずに済み、比較が悪い側の検出か良い側の検出かが常に名前に残る。
function measureLines(measures: Measures): string[] {
  const lines: string[] = [];
  const entries = Object.values(measures).sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  for (const measure of entries) {
    const thresholds = measure.thresholds ?? [];
    if (thresholds.length === 0) {
      continue;
    }
    lines.push("");
    lines.push(`  // ${measure.preferredName} (${measure.id}): ${polarityLabel(measure.polarity)}`);
    if (worseSide(measure.polarity) === undefined) {
      lines.push(
        `  // 極性が ${measure.polarity} のため、悪い側を決める述語は生成しません` +
          "(向きが決まってから再生成してください)",
      );
      continue;
    }
    for (const threshold of thresholds) {
      if (!Number.isInteger(threshold.at)) {
        lines.push(
          `  // ${threshold.preferredName}: 閾値 ${threshold.at} は整数でないため述語を生成しません` +
            "(Quint側で抽象化してください)",
        );
        continue;
      }
      // 比較の向きはCUEの極性から導出する(ここで書き分けない)。
      const comparison = worseSideComparison(measure.polarity, threshold.inclusive);
      if (comparison === undefined) {
        continue;
      }
      const names = thresholdQuintNames(threshold.id);
      lines.push(`  /// ${renderThreshold(measure, threshold)}`);
      lines.push(`  pure val ${names.at}: int = ${threshold.at}`);
      lines.push(
        `  pure def ${names.isWorseSide}(value: int): bool = value ${comparison} ${names.at}`,
      );
      lines.push(
        `  pure def ${names.isBetterSide}(value: int): bool = not(${names.isWorseSide}(value))`,
      );
    }
  }
  return lines;
}

export function generateConstants(
  ids: string[],
  moduleName: string,
  measures?: Measures,
): string {
  const sorted = [...ids].sort();
  const lines: string[] = [
    "// GENERATED by tools/gen-quint-constants. DO NOT EDIT.",
    "// 語彙の原本はCUE(spec/*.cue)にある。再生成:",
    "//   tools/gen-quint-constants <specパス>",
    "",
    `module ${moduleName} {`,
  ];
  for (const id of sorted) {
    lines.push(`  pure val ${toQuintName(id)}: str = ${JSON.stringify(id)}`);
  }
  lines.push("");
  lines.push(
    `  pure val knownIds: Set[str] = Set(${sorted.map((id) => JSON.stringify(id)).join(", ")})`,
  );
  if (measures !== undefined) {
    lines.push(...measureLines(measures));
  }
  lines.push("}", "");
  return lines.join("\n");
}
