import { spawnSync } from "node:child_process";
import { resolve } from "node:path";

export type KnownIdInfo = {
  ids: string[];
  moduleName: string;
};

// cwd非依存にするため、specディレクトリをcwdにして "." を渡す。
export function fetchKnownIds(specPath: string): string[] {
  const result = spawnSync("cue", ["export", ".", "-e", "knownIds"], {
    cwd: resolve(specPath),
    encoding: "utf-8",
  });
  if (result.status !== 0) {
    throw new Error(`cue export failed:\n${result.stderr}`);
  }
  return JSON.parse(result.stdout) as string[];
}

export function moduleNameFor(specPath: string): string {
  const segments = specPath.split("/").filter(Boolean);
  const base = segments.pop() ?? "spec";
  // spec ディレクトリの直親をアプリ名とみなす。
  let appDir = base === "spec" ? segments[segments.length - 1] : base;
  // 既定の <project>/keaton/spec のように直親が keaton なら、
  // その一つ上(プロジェクト名)を使う。
  if (appDir === "keaton") {
    appDir = segments[segments.length - 2] ?? appDir;
  }
  return `${toIdentifier(appDir ?? "spec")}Constants`;
}

// アプリディレクトリ名から有効なQuint識別子を作る。
// ハイフン等の非英数字で区切り、各片の先頭を大文字にして繋ぐ。
// 例: "momotaro"→"Momotaro", "todo-cli"→"TodoCli"
function toIdentifier(name: string): string {
  const parts = name.split(/[^a-zA-Z0-9]+/).filter((part) => part.length > 0);
  if (parts.length === 0) {
    return "Spec";
  }
  return parts.map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

export function toQuintName(id: string): string {
  const parts = id.split("-").filter((part) => part.length > 0);
  if (parts.length === 1) {
    return parts[0];
  }
  return parts
    .map((part, index) =>
      index === 0 ? part : part[0].toUpperCase() + part.slice(1),
    )
    .join("");
}

export function generateConstants(ids: string[], moduleName: string): string {
  const sorted = [...ids].sort();
  const lines: string[] = [
    "// GENERATED by tools/gen-quint-constants. DO NOT EDIT.",
    "// 語彙の原本はCUE(spec/*.cue)にある。再生成:",
    "//   tools/gen-quint-constants <specパス>",
    "",
    `module ${moduleName} {`,
  ];
  for (const id of sorted) {
    lines.push(`  pure val ${toQuintName(id)}: str = ${JSON.stringify(id)}`);
  }
  lines.push("");
  lines.push(
    `  pure val knownIds: Set[str] = Set(${sorted.map((id) => JSON.stringify(id)).join(", ")})`,
  );
  lines.push("}", "");
  return lines.join("\n");
}
